### ISSUE TITLE
Internet down at HPC?

### ISSUE THREAD

**Issue by h4duan** [AMDResearch/hpcfund#12]
It seems that there are some internet issues in HPC. I cannot load the model from huggingface today. Got the error "OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like facebook/esm2_t33_650M_UR50D is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode.". The code worked fine yesterday.

**Comment by h4duan** [comment]
also got the error "salloc: error: Job submit/allocate failed: Socket timed out on send/recv operation" when asking for an interactive session.

**Comment by koomie** [comment]
Thanks for the report.  We are seeing this as well (it started this morning) and there are some ongoing background network issues that are preventing SLURM jobs from launching successfully.  We are working to get it resolved with the data center technicians but I don't have an ETA just yet.  


Apologies for the interruption, I will follow up when the network is cooperating again.

**Comment by koomie** [comment]
FYI, the networking issue encountered earlier today has been resolved.  As a result, the queue's have been opened back up for scheduling so future jobs should be back in business.

Apologies again for the interruption.
