### ISSUE TITLE
cannot submit jobs to mi1008x

### ISSUE THREAD

**Issue by h4duan** [AMDResearch/hpcfund#13]
Hi,

The jobs I submitted to mix1008x got into queue with the reason "resource". However, i checked that there are only 4 mi1008x nodes being used. Do you know what might be the issue?

**Comment by h4duan** [comment]
![Screenshot 2023-12-21 at 10 35 02 AM](https://github.com/AMDResearch/hpcfund/assets/57917036/50ff4fd3-4a45-44a9-aaa4-eadb70957079)

**Comment by koomie** [comment]
Yes, some hosts are disabled from the queue to go thru a software upgrade. Your job will schedule when additional 8way hosts are returned to production or other user jobs finish.
