### ISSUE TITLE
launching HIP compiler

### ISSUE THREAD

**Issue by gorgW** [AMDResearch/hpcfund#2]
I am trying to run 4 openmm simulations simultaneously in parallel on the same node, one at each GPU -since mi1004x has 4 and mi1008x has 8- using this loop 
for i in `seq 0 3`
do
        mkdir $i
        cd $i
        python3 $execname $i &> slurmout.run.$SLURM_JOB_ID &
        cd -
done
where $i runs over GPU index and  $execname is the python file.
The issue is getting this error when I make the loop runs till 3 or more 
"openmm.OpenMMException: Error launching HIP compiler: 32512"

The job works well when the max number in the loop is 2. 
Also this happens whatever the partition I am using (devel and mi1004x and mi1008x ) either in interactive job or using bash file.

**Comment by gorgW** [comment]
I face the same error ( I believe it is related ) in the following situation
after creating .sif file for openmm
i run this 
singularity run ./openmm.sif run-benchmarks

it gives this error: 
Test failed: Error launching HIP compiler: 32512
Can't exec "/opt/rocm-5.4.2/llvm/bin/clang": No such file or directory at /opt/rocm-5.0.0/bin/hipcc line 156.

**Comment by gorgW** [comment]
The problem is solved partially when I added this line to the bash script 
ulimit -v 128000000
and by partially I mean that some some simulations work and some give the same error

and the problem is solved completely when i added this " sleep 10 " 
inside the loop. 
Is there a way it can be solved fundamentally or these lines are necessary in the current case ?

**Comment by koomie** [comment]
Let me look into this a bit.  I suspect you may need to bump up the virtual memory limit even more. Can you point me to an example job script so I can reproduce?

**Comment by koomie** [comment]
I have updated the compute environment to bump up the virtual memory limit to be `unlimited`.  @gorgW, is your problem running ok now?  If not, can you please point me to an example job script and associated collateral so that I can try to reproduce?

**Comment by gorgW** [comment]
It works well now. 

Thanks.
