### ISSUE TITLE
Running multiple scripts on a node

### ISSUE THREAD

**Issue by imkevinkuo** [AMDResearch/hpcfund#20]
I am attempting to run multiple copies of a PyTorch python script in parallel e.g. one copy for each of the 4 gpus on a mi1004x node. I am currently attempting to do this by:
1. opening an interactive shell on devel / mi1004x with `salloc`
2. using a helper script which uses `subprocess.Popen()` to run an non-blocking instance of the training script
3. within the training script, I set `os.envrion['CUDA_VISIBLE_DEVICES']` to the GPU id I want to use.

This seems to work for running up to 3 jobs in parallel, but when trying to run a 4th job (which should be possible as there is a 4th GPU free), I encounter the following error: `Check failed: ret == 0 (11 vs. 0)Thread tf_Compute creation via pthread_create() failed`. Could it be that I need to add a certain flag(s) during step 1. so that each traning script has adequate CPU resources?

**Comment by tom-papatheodore** [comment]
Hello. It's difficult to tell what the problem is without seeing your script. Are the multiple copies of your PyTorch script independent, or do they need to communicate somehow? If the former, you could use a wrapper script such as the one below to divide up the CPUs and GPUs among the 4 processes that launch the individual scripts. If the latter, I'll need to see your script to better understand the issue.

NOTE: You wouldn't need the `OMP_NUM_THREADS=1` in the wrapper script below unless you were using OpenMP, which I don't believe you are.

-Tom


```
$ cat cpu_gpu_map.sh
#!/bin/bash

local_rank_id=${SLURM_LOCALID}
OMP_NUM_THREADS=1

case $local_rank_id in
    0)
        export ROCR_VISIBLE_DEVICES=0
        numactl --physcpubind=0 $1
        ;;
    1)
        export ROCR_VISIBLE_DEVICES=1
        numactl --physcpubind=8 $1
        ;;
    2)
        export ROCR_VISIBLE_DEVICES=2
        numactl --physcpubind=16 $1
        ;;
    3)
        export ROCR_VISIBLE_DEVICES=3
        numactl --physcpubind=24 $1
        ;;
    *)
        printf "This script only supports up to 4 processes"
        exit 1
        ;;
esac


$ srun -n4 ./cpu_gpu_map.sh ./hello_jobstep | sort
MPI 000 - OMP 000 - HWT 000 - Node t006-006.hpcfund - RT_GPU_ID 0 - GPU_ID 0 - Bus_ID e3
MPI 001 - OMP 000 - HWT 008 - Node t006-006.hpcfund - RT_GPU_ID 0 - GPU_ID 1 - Bus_ID c3
MPI 002 - OMP 000 - HWT 016 - Node t006-006.hpcfund - RT_GPU_ID 0 - GPU_ID 2 - Bus_ID a3
MPI 003 - OMP 000 - HWT 024 - Node t006-006.hpcfund - RT_GPU_ID 0 - GPU_ID 3 - Bus_ID 83
```

**Comment by imkevinkuo** [comment]
Thanks for the prompt reply!

Each script is independent. However, I'm specifically interested in running a large number of trials e.g. 40 and starting a new run as soon as a gpu is idle. My temporary solution is to query `rocm-smi` within my python helper script and check the memory usage. This works fine when I don't have more than 3 scripts running at once, but for some reason submitting a 4th one leads to the issue noted in the original post.

On another cluster that uses SLURM which does not have the restriction of one SLURM job per node, I could do this easily by submitting a single-gpu SLURM job for each instance of the training script. I also noticed that sbatch flags such as `gres` or `gpus` don't work on the hpcfund cluster. Is there a way to change the cluster settings that can accomodate my use case without negatively affecting others?

For some reason, I also found that setting `os.environ['OMP_NUM_THREADS']=1` within the training script was necessary in order to have more than one job running at a time on the same node. From some other searches it seems like this error is due to insufficient / incorrectly allocating CPU resources / RAM on the node.

**Comment by tom-papatheodore** [comment]
Hey Kevin. Would you be willing to share your script with me? I think that would be the easiest way for me to help with this. I can grab a copy from the cluster if you tell me where it's located.

**Comment by imkevinkuo** [comment]
Hi Tom, I think I have found a solution which is to still use an interactive session with `salloc` and then run `sun --exclusive --ntasks 1 python train.py ...` rather than directly running `python train.py`. This seems to work OK on the 4x nodes so I'll close the issue for now.

In case it is helpful for future users, here are critical snippets of the code:
```
# train_sweep.py
import os
import time
import subprocess
from sys import stdout
from tqdm import tqdm

def run_job(args_dict, gpu):
    main_command = ['srun', '--exclusive', '--ntasks', '1', 'python3','train.py']
    args_dict.update({'gpu': str(gpu)})
    whole_command = main_command
    for k, v in args_dict.items():
        whole_command.append('--' + str(k))
        whole_command.append(str(v))
    print(whole_command)
    subprocess.Popen(args=whole_command)

def min_gpu(gpus, threshold):
    device_counts = {g:0 for g in gpus}
    output_lines = os.popen(f"rocm-smi --showmeminfo vram").read().split('\n')
    for line in output_lines:
        if 'VRAM Total Used Memory' in line:
            toks = line.split()
            mem = int(toks[-1]) / 1e9 # GB
            gpu = int(toks[0][-2])
            if mem > 1: # 1 GB
                device_counts[gpu] = 1
                
    argmin = min(device_counts.keys(), key=lambda x: device_counts[x])
    if device_counts[argmin] >= threshold:
        return -1
    else:
        return argmin
    
def acquire_gpu(gpus, threshold=1):
    i = 0
    gpu = min_gpu(gpus=gpus, threshold=threshold)
    while gpu == -1:
        stdout.write("\rWaiting on gpu for: {0}s".format(i))
        i += 30
        time.sleep(30)
        gpu = min_gpu(gpus=gpus, threshold=threshold)
    stdout.write("\n")
    return gpu

GPUS = [i for i in range(4)]
for config in configs: # configs is a list of dictionaries mapping arguments to values
    gpu = 3 - acquire_gpu(GPUS) # rocm-smi and CUDA_VISIBLE_DEVICES are reversed for some reason
    run_job(config, gpu)
    time.sleep(15)
```

```
# train.py
os.environ['OMP_NUM_THREADS'] = '1'
# apparently any one of these three lines has the same effect
os.environ['CUDA_VISIBLE_DEVICES'] = args.gpu
# os.environ['ROCR_VISIBLE_DEVICES'] = args.gpu
# os.environ['HIP_VISIBLE_DEVICES'] = args.gpu
```

**Comment by tom-papatheodore** [comment]
Glad to hear you were able to find a solution. And thanks for sharing the results for future users.
