### ISSUE TITLE
amdsmi_get_energy_count() returns the same value

### ISSUE THREAD

**Issue by parthraut** [AMDResearch/hpcfund#21]
Hello! So I am currently involved in bringing AMD GPU support to the [Zeus Project](https://ml.energy/zeus/).

We are using ROCM 6.0.2 and testing on [AMD HPC Fund](https://amdresearch.github.io/hpcfund/) Cluster, specifically on an MI100.

We are using [amdsmi_get_energy_count()](https://rocm.docs.amd.com/projects/amdsmi/en/latest/py-interface_readme_link.html#amdsmi-get-energy-count) to query the energy consumption of the GPU while training. However, the values returned seem to not be updating, resulting in no change in energy consumption, as shown below:

```
>>> import amdsmi
>>> amdsmi.amdsmi_init()
>>> handles = amdsmi.amdsmi_get_processor_handles()
>>> amdsmi.amdsmi_get_energy_count(handles[0])
{'power': 8152136, 'counter_resolution': 15.300000190734863, 'timestamp': 3824190842400799}
>>> amdsmi.amdsmi_get_energy_count(handles[0])
{'power': 8152136, 'counter_resolution': 15.300000190734863, 'timestamp': 3824190842400799} # returns the same power value
```

Even while fully utilizing the GPU during a pytorch training script, there seems to be no difference in the return value, resulting in the calculated energy consumption to be 0 always. 

I noticed that in the documentation, it mentions: **"It is not supported on virtual machine guest"**. Does this apply to the environment in the cluser? Or is there something else that needs to be done for it to return an updated value?

**Comment by parthraut** [comment]
Looks like upgrading to ROCM 6.1 fixes this issue, as detailed in [this](https://github.com/ROCm/amdsmi/issues/22). 

The cluser looks like it has 5.4.2, 5.5.1, 5.7.1, & 6.0.2. Would an admin be able to install 6.1 in the cluster? Then this issue can be resolved.

Thank you!

**Comment by koomie** [comment]
Yes, we can land a driver upgrade.  I have scheduled a maintenance window for June 5 to land a newer ROCm version.

**Comment by koomie** [comment]
ROCm 6.1.2 is live across the board now.
