### ISSUE TITLE
2815415 Segmentation fault  

### ISSUE THREAD

**Issue by gorgW** [AMDResearch/hpcfund#3]
I got this error 
/path/execnew.sh: line 3: 2815415 Segmentation fault      (core dumped) python3 /path/run.py $1
When I use sbatch to run a job where I use 4 GPUs for my job.
#!/bin/bash -l
#SBATCH --job-name=example
#SBATCH --nodes=1
#SBATCH --export=ALL
#SBATCH --time=24:00:00
#SBATCH -p mi1004x

 I think there is nothing wrong with my script because this error happens only with one node of mi1004x which is t006-002.  
Also I get the same error with some of mi1008x and sometimes another error with only the last GPU in the mi1008x that I can't reproduce now. I should mention that the same script was working well till a month ago and it works well with some nodes, this is why i think it is not a script problem.

**Comment by koomie** [comment]
Thanks for the report.  Can you possibly setup a directory under your account somewhere with the full job script and any additional collateral (files, scripts, etc) needed to run.  I will copy those and see if I can reproduce to try and see what might be going on.

Thanks.

**Comment by gorgW** [comment]
the path that has everything is /work1/whitford/george/error
Paths needs to be changed are
in run.py file "FFdir" variable should point to the path of run.py file itself
in submit.run.bash file  "container" variable should point to the path of openmm.sif file
and WORK_DIR variable should point to the path of submit.run.bash file itself

in execnew.sh file 
source /path_of_venv_file/venv/containers/openmm/bin/activate
where venv file is included in the path /work1/whitford/george/error
then
python3 /path_of_run.py_file/run.py 
which is the same path where execnew.sh exists in. 

all this for using #SBATCH -p mi1004x
with a loop in submit.run.bash that run 4 parallel simulations "for i in `seq 0 3`"

so you can also change both to  #SBATCH -p mi1008x and for i in `seq 0 7`
for 8 GPUs

Thanks.

**Comment by koomie** [comment]
Quick followup question.  I was able to get your case running in my own directory - there seemed to be one additional step missing for me which was to install the `OpenSMOG` library using pip/python that resided in the container.  

Now, for the question. When you were seeing the segfault, does it happen right away, or does it take a while?  In particular, if I see output like the following, are we passed the point were you segfaulted previously?

```
Creating Nonbonded force 0 from xml file
Loaded force field and config files.
0.62
#"Progress (%)" "Step"  "Speed (ns/day)"        "Time Remaining"
0.0%    100000  0       --
0.0%    200000  1.74e+03        4:14:07:00
0.0%    300000  1.74e+03        4:14:01:46
0.0%    400000  1.75e+03        4:13:55:49
```

**Comment by koomie** [comment]
Also, I haven't been able to access the node you mentioned (`t006-002`) just yet as it is busy running other jobs. But I will hopefully get to schedule a job there and see if I can reproduce.

Note that you can also skip nodes in your request for the time being if you want.  To do that, you can add a line like the following to your submission script

```
#SBATCH -x t006-002
```

**Comment by koomiefoo** [comment]
I think I answered my own question as I was able to reproduce on `t006-002`.  Turns out that host's GPU driver was in a bad way and has been reloaded.  I've added some additional logic to look for similar issues in the future and will take the node out of production.  

Thanks for reporting the issue with this particular host.
