### ISSUE TITLE
How to Get Docker Access

### ISSUE THREAD

**Issue by zixianwang2022** [AMDResearch/hpcfund#32]
Hi, 

I am wondering how can we get docker access on HPC Fund?

**Comment by koomie** [comment]
Docker is not available due to the elevated credentials required. However, this is an alternative container solution available named `appraiser` that is installed system wide.  You can convert existing docker containers to apptainer for use locally.

https://apptainer.org/docs/user/latest/

**Comment by cameronshinn** [comment]
Hi @koomie would it be possible to use something like [pyxis](https://github.com/NVIDIA/pyxis) to accomplish this? AMD has been very supportive of docker and is the best way to run much of their software (vLLM in my case). Seeing that reflected in the HPC fund cluster would be very appreciated. Sorry to re-raise this issue, cheers.
