### ISSUE TITLE
Raising ulimit on Compute Node

### ISSUE THREAD

**Issue by zixianwang2022** [AMDResearch/hpcfund#33]
Hi, 

I am running MIGraphX's compile model, but I am getting `out of resource error`. It turns out that I have to increase the total number available threads. But when I run 

```
(mlperf_1) [ziw081@t008-004 ziw081]$ ulimit -u 60000
bash: ulimit: max user processes: cannot modify limit: Operation not permitted
```
It says operation not permitted.

**Comment by koomie** [comment]
I can't imagine a compelling performance reason to want to spawn 60000 threads on a system with 128 physical cores.
