### ISSUE TITLE
Tensorflow/Keras

### ISSUE THREAD

**Issue by valtercv** [AMDResearch/hpcfund#5]
It would be very useful for us if you may provide Tensorflow/Keras wth GPU support

**Comment by koomie** [comment]
Have you installed this before? You are welcome to install packages in your own $HOME or $WORK directories, or alternatively if there is a pre-existing container with the desired tensorflow variant you can convert docker containers to singularity and run them on the system.

**Comment by valtercv** [comment]
Yes, I did the installation locally for myself. I may try to do the same on the cluster. I just thought that, maybe, this could be of interest of other people, in that case it would be probably better to have a centralized installation.

**Comment by koomie** [comment]
Definitely agree!  Happy to work on a shared installation, but just wanted to make sure you were able to progress without it.  I'll put it on the TODO list and hopefully you might be able to help test a centralized install.

**Comment by valtercv** [comment]
I tried to install the package following the instruction for Ubuntu, here [https://rocm.docs.amd.com/en/latest/how_to/tensorflow_install/tensorflow_install.html](url) but it seems that there is the need to do something at the system level. All I got is " Cannot dlopen some GPU libraries." One suggestion is to install  rocm-dkms, rocm-libs and rccl  (don't know if it works)

**Comment by koomie** [comment]
Just a head's up that we have made a shared install of the rocm variant of tensorflow available on the cluster.  To access from a default login, issue:

`module load tensorflow`

At at that point, you should be able to import, e.g:

```
[atest@login1 ]$ python3
Python 3.9.14 (main, Jan  9 2023, 00:00:00) 
[GCC 11.3.1 20220421 (Red Hat 11.3.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
2023-09-19 11:32:21.641493: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
>>> 
```

Hopefully you can give it a try and let us know if you encounter unexpected issues.

**Comment by valtercv** [comment]
Thank you!
I did jut a few basic checks and everything seems to work as expected. I will post here if any issues arise while computing more complicated things.
